name: page_analyzer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    env:
      DATABASE_URL: "postgres://localhost/postgres"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql

      - name: Start PostgreSQL
        run: |
          sudo service postgresql start

      - name: Create test database
        run: |
          sudo -u postgres createdb python-project-83

      - name: Install poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make build

      - name: Run linter and pytest
        run: |
          make lint
          make pytest

      - name: Test coverage
        uses: paambaati/codeclimate-action@v3.1.1
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
